### PR TITLE
Add github workflow for release

### PR DESCRIPTION
**Pull request by ericpre**
This workflow do the following:
- Create release on tag
- update version from the tag
- build sdist and bdist
- run test suite with this release package
- upload tarball and wheel as github artifact
- upload to pypi (only from `hyperspy/hyperspy_gui_traitsui` repository)

One missing thing is to set the `secrets.pypi_password` in the settings of the repository. @francisco-dlp, it you can set it the `secrets.pypi_password` as describe in https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/#saving-credentials-on-github, I think it would be good to do a release to test it - particularly since https://github.com/hyperspy/hyperspy_gui_traitsui/pull/30 can be annoying for users.

### CODE REVIEW

**Comment by ericpre** [comment]
Example of build: https://github.com/ericpre/hyperspy_gui_traitsui/actions/runs/223486677

**Comment by ericpre** [comment]
Some more changes:
- add a script to set the release and development version. This script can also process changelog, useful for hyperspy, but not used here. I think it would be good to move this script to `hyperspy/ci-scripts` and clone it in the github workflow.
- add `RELEASING_GUIDE.md`

**Comment by jlaehne** [comment]
Looking forward to having proper releases of the GUI packages again (as they are stuck on v1.1.1)
:-)

**Review by tjof2 — APPROVED** [review]

**Comment by ericpre** [comment]
@jlaehne, there is a tag for `v1.3.1` now. Is it good enough, or is a Github release required?

I will revisit this PR for the next release.

**Comment by jlaehne** [comment]
@ericpre, the important thing is that there is a v.x.x.x.zip file available, which there now is for v.1.3.1 

So I can update the AUR package tomorrow (at the moment it was downloading master.zip, but with every merge the SHA-key changes and would have to be changed).

**Comment by ericpre** [comment]
Would it be better to use the source distribution from pypi? The sha256 is also available from pypi, so you will not need to get it manually.

**Comment by jlaehne** [comment]
> Would it be better to use the source distribution from pypi? The sha256 is also available from pypi, so you will not need to get it manually.
The download links from pypi are more complicated than for github (where only the version number changes). I can copy paste the hash from pypi, but do not see a way so far to automatically source it from there.

**Comment by ericpre** [comment]
> > Would it be better to use the source distribution from pypi? The sha256 is also available from pypi, so you will not need to get it manually.
> 
> The download links from pypi are more complicated than for github (where only the version number changes). I can copy paste the hash from pypi, but do not see a way so far to automatically source it from there.

This is slightly more complicated but it follows a specific pattern with only the version changing.
See https://github.com/conda-forge/hyperspy-gui-traitsui-feedstock/blob/4255d8d5ff80a397656f2211a0547eb25fdb0c8f/recipe/meta.yaml#L1-L14

If I remember correctly, the hash of github changes sometimes - don't remember if this is from the tag or the release... 

It seems that there are a few tools to get the hash from pypi and the information is accessible from this json:
https://pypi.org/pypi/hyperspy-gui-ipywidgets/json

**Comment by ericpre** [comment]
Move simple version in #32.

**Pull request closed without merging**
