### PR TITLE
Improve image contrast tool

### PR DESCRIPTION
**Pull request by ericpre**
For https://github.com/hyperspy/hyperspy/pull/2272:
- [x] replace saturated_pixels by percentiles,
- [x] tweak formatting float,
- [x] ready for review.

### CODE REVIEW

**Comment by francisco-dlp** [comment]
The tests pass, but this is broken :(

```python
Traceback (most recent call last):
  File "/home/francisco/anaconda/miniforge/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 224, in process
    func(*args, **kwargs)
  File "/home/francisco/Git/hyperspy/hyperspy/drawing/image.py", line 614, in on_key_press
    self.gui_adjust_contrast()
  File "/home/francisco/Git/hyperspy/hyperspy/drawing/image.py", line 586, in gui_adjust_contrast
    return ceditor.gui(display=display, toolkit=toolkit)
  File "/home/francisco/Git/hyperspy/hyperspy/ui_registry.py", line 164, in pg
    toolkit=toolkit, **kwargs)
  File "/home/francisco/Git/hyperspy/hyperspy/ui_registry.py", line 138, in get_gui
    thisw = f(obj=self, display=display, **kwargs)
  File "/home/francisco/anaconda/miniforge/lib/python3.6/site-packages/hyperspy_gui_traitsui/utils.py", line 11, in wrapper
    obj.edit_traits(**kwargs)
  File "/home/francisco/anaconda/miniforge/lib/python3.6/site-packages/traits/has_traits.py", line 1678, in edit_traits
    args,
  File "/home/francisco/anaconda/miniforge/lib/python3.6/site-packages/traitsui/view.py", line 462, in ui
    ui.ui(parent, kind)
  File "/home/francisco/anaconda/miniforge/lib/python3.6/site-packages/traitsui/ui.py", line 246, in ui
    self.rebuild(self, parent)
  File "/home/francisco/anaconda/miniforge/lib/python3.6/site-packages/traitsui/qt4/toolkit.py", line 162, in ui_live
    ui_live.ui_live(ui, parent)
  File "/home/francisco/anaconda/miniforge/lib/python3.6/site-packages/traitsui/qt4/ui_live.py", line 43, in ui_live
    _ui_dialog(ui, parent, BaseDialog.NONMODAL)
  File "/home/francisco/anaconda/miniforge/lib/python3.6/site-packages/traitsui/qt4/ui_live.py", line 65, in _ui_dialog
    BaseDialog.display_ui(ui, parent, style)
  File "/home/francisco/anaconda/miniforge/lib/python3.6/site-packages/traitsui/qt4/ui_base.py", line 284, in display_ui
    ui.owner.init(ui, parent, style)
  File "/home/francisco/anaconda/miniforge/lib/python3.6/site-packages/traitsui/qt4/ui_live.py", line 225, in init
    self.add_contents(panel(ui), bbox)
  File "/home/francisco/anaconda/miniforge/lib/python3.6/site-packages/traitsui/qt4/ui_panel.py", line 259, in panel
    panel = _GroupPanel(content[0], ui).control
  File "/home/francisco/anaconda/miniforge/lib/python3.6/site-packages/traitsui/qt4/ui_panel.py", line 599, in __init__
    layout = self._add_groups(content, inner)
  File "/home/francisco/anaconda/miniforge/lib/python3.6/site-packages/traitsui/qt4/ui_panel.py", line 680, in _add_groups
    panel = _GroupPanel(subgroup, self.ui).control
  File "/home/francisco/anaconda/miniforge/lib/python3.6/site-packages/traitsui/qt4/ui_panel.py", line 601, in __init__
    layout = self._add_items(content, inner)
  File "/home/francisco/anaconda/miniforge/lib/python3.6/site-packages/traitsui/qt4/ui_panel.py", line 867, in _add_items
    ui, object, name, item.tooltip, None
  File "/home/francisco/anaconda/miniforge/lib/python3.6/site-packages/traitsui/editor_factory.py", line 137, in simple_editor
    description=description,
  File "/home/francisco/anaconda/miniforge/lib/python3.6/site-packages/traitsui/editor.py", line 463, in __init__
    self.old_value = getattr(self.object, self.name)
AttributeError: 'ImageContrastEditor' object has no attribute 'saturated_pixels'
```

**Comment by francisco-dlp** [comment]
No, it works fine: I was not in the right branch.

There is an issue though: ``vmin`` should always be ``< vmax``

**Comment by francisco-dlp** [comment]
I wouldn't know how to fix this since ``traitsui`` doesn't seem to have the equivalent of a ``FloatRangeSlider``. The issue is that when vmax < vmin errors are raised if ipywidgets is enabled. If not, then there are no errors, but it is not clear to me what's going on with the contrast.

**Comment by ericpre** [comment]
I am going to try to fix it with:

```python
from traits.api import HasTraits, Float
from traitsui.api import View, Item
from traitsui.qt4.extra.bounds_editor import BoundsEditor

class Foo(HasTraits):
    first = Float(10)
    last = Float(20)

    traits_view = View(Item('first',
                            editor=BoundsEditor(
                                    low_name='first',
                                    high_name='last')),
      )

    def _incr_low_changed(self):
        self.first += 1

    def _first_changed(self, old, new):
        print("first:", self.first)

    def _last_changed(self, old, new):
        print("last", self.last)
```

**Comment by francisco-dlp** [comment]
I find it a bit risky for this release. I will be fully offline from tomorrow morning and I would like to avoid last minute surprises. What about merging as is, filling a bug report and fixing it in the next patch release?

**Comment by ericpre** [comment]
This seems to be working fine for me.

**Comment by francisco-dlp** [comment]
That's perfect, I didn't know that that editor existed.

**Pull request merged**
