### PR TITLE
Make axes gui compatible with non-linear-axis

### PR DESCRIPTION
**Pull request by jlaehne**
### Description of the change

Gui for axes failed when `offset` or `scale` parameters were missing. Added checks for existance of these attributes to make the gui compatible with [hyperspy-PR#1927](https://github.com/hyperspy/hyperspy/pull/1927) now continued in the [non-uniform-axes branch](https://github.com/hyperspy/hyperspy/tree/non_uniform_axes).

### Progress of the PR:

- [X] Change implemented and tested
- [X] Ready for review

### CODE REVIEW

**Comment by ericpre** [comment]
@jlaehne, we need to start to add tests, do you want to add some covering the axes gui in this PR?

**Comment by jlaehne** [comment]
Good point. I can at least try ;-)

**Comment by jlaehne** [comment]
@ericpre I realize that I have not much experience with the GUI elements, so as long as there are basically no other traitsui tests it might take a while before I manage to write tests for the axes.

**Comment by ericpre** [comment]
@jlaehne: I made a PR (https://github.com/jlaehne/hyperspy_gui_traitsui/pull/1) to add tests to this branch.

A few suggetions:
- in case of `DataAxis`, the calibration group should not be displayed
- in case of `FunctionalDataAxis`, we could display the calibration group with the parameter of the function

On a side note, I suspect some of the ipywidgets guis may not be working with non uniform axis. I noticed it when running the tests added in https://github.com/jlaehne/hyperspy_gui_traitsui/pull/1.

**Comment by jlaehne** [comment]
@ericpre 
>     * in case of `DataAxis`, the calibration group should not be displayed
Good point, implemented.
 
>     * in case of `FunctionalDataAxis`, we could display the calibration group with the parameter of the function
Now displays not only the expression, but allows to edit the parameters of the expression and in case that `x` is a `UniformDataAxis` also `scale` and `offset` of that axis.

> On a side note, I suspect some of the ipywidgets guis may not be working with non uniform axis. I noticed it when running the tests added in [jlaehne#1](https://github.com/jlaehne/hyperspy_gui_traitsui/pull/1).
I have to get my ipywidgets running again, but then I could test them and port the changes just added here

**Review by ericpre — APPROVED** [review]
Nice!

**Pull request merged**
